// Generated by npm run api:generate. Do not edit manually.
export interface components {
  schemas: {
    /** Advance */
    Advance: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Steps
       * @default 1
       */
      steps?: number
    }
    /** Answer */
    Answer: {
      /** Confidence */
      confidence?: number | null
      /** Option Id */
      option_id: string
      /** Question Id */
      question_id: string
    }
    /** Create */
    app__challenges__api__Create: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Mode
       * @default practice
       * @enum {string}
       */
      mode?: 'practice' | 'daily' | 'chapter_entry' | 'chapter_exit'
      /** Module Id */
      module_id?: string | null
      /**
       * Opponent Count
       * @default 1
       */
      opponent_count?: number
    }
    /** Command */
    app__economy__Command: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Policy Version
       * @default 1
       * @constant
       */
      policy_version?: '1'
    }
    /** Command */
    app__learning_runs__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Join */
    app__multiplayer__api__Join: {
      /** Code */
      code: string
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Command */
    app__quizzes__api__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Join */
    app__quizzes__api__Join: {
      /** Idempotency Key */
      idempotency_key: string
      /** Join Code */
      join_code: string
    }
    /** Command */
    app__research__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Command */
    app__simulation__api__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Create */
    app__simulation__api__Create: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Mode
       * @default guided
       * @enum {string}
       */
      mode?: 'guided' | 'endless'
    }
    /** Audit */
    Audit: {
      /** Engine Version */
      engine_version: number
      /** No Order Reason */
      no_order_reason: ('no_thesis_supplied' | 'current_ask_above_cap') | null
      /** Observation Token */
      observation_token?: string | null
      /** Orders */
      orders: components['schemas']['AuditOrder'][]
      /** Price Limit Guarantees Fill */
      price_limit_guarantees_fill: boolean
      /** Session Fees */
      session_fees: string
      /** Tick */
      tick: number
    }
    /** AuditOrder */
    AuditOrder: {
      /** Filled Quantity */
      filled_quantity: number
      /** Limit Price */
      limit_price: string
      /** Order Id */
      order_id: string
      /**
       * Status
       * @enum {string}
       */
      status:
        'open' | 'partial' | 'filled' | 'cancelled' | 'expired' | 'rejected'
    }
    /** Claim */
    Claim: {
      /** Idempotency Key */
      idempotency_key: string
      /** Item Id */
      item_id: string
    }
    /** Consent */
    Consent: {
      /** Accepted */
      accepted: boolean
      /** Idempotency Key */
      idempotency_key: string
      /** Policy Digest */
      policy_digest: string
      /** Policy Version */
      policy_version: string
    }
    /** CreateRoom */
    CreateRoom: {
      /**
       * Attempt Limit
       * @default 1
       */
      attempt_limit?: number
      /** Idempotency Key */
      idempotency_key: string
      /** Question Ids */
      question_ids: string[]
      /** Title */
      title: string
    }
    /** Debrief */
    Debrief: {
      /** Idempotency Key */
      idempotency_key: string
      /** Reflection */
      reflection: string
    }
    /** Equipment */
    Equipment: {
      /** Avatar Id */
      avatar_id?: string | null
      /** Idempotency Key */
      idempotency_key: string
      /** Title Id */
      title_id?: string | null
    }
    /** FirebaseAuthConfig */
    FirebaseAuthConfig: {
      /** Firebase Project Id */
      firebase_project_id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      mode: 'firebase'
    }
    /** GuestAuthConfig */
    GuestAuthConfig: {
      /** Firebase Project Id */
      firebase_project_id: null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      mode: 'guest'
    }
    /** GuestSession */
    GuestSession: {
      /**
       * Auth Mode
       * @constant
       */
      auth_mode: 'guest'
      /** Expires At */
      expires_at: string
      /** Profile Id */
      profile_id: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** JournalCreate */
    JournalCreate: {
      /** Lesson Id */
      lesson_id?: string | null
      /** Text */
      text: string
    }
    /** Metadata */
    Metadata: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Prior Knowledge
       * @enum {string}
       */
      prior_knowledge: 'unknown' | 'none' | 'some' | 'experienced'
    }
    /** Order */
    Order: {
      /** Idempotency Key */
      idempotency_key: string
      plan: components['schemas']['Plan']
      /** Price */
      price?: string | null
      /** Quantity */
      quantity: number
      /**
       * Side
       * @enum {string}
       */
      side: 'buy' | 'sell'
      /**
       * Symbol
       * @enum {string}
       */
      symbol: 'NORTH' | 'HARBOR' | 'PLAIN' | 'COVE'
      /**
       * Type
       * @enum {string}
       */
      type: 'market' | 'limit' | 'stop'
    }
    /** Plan */
    Plan: {
      /** Exit */
      exit: string
      /** Max Loss */
      max_loss: string
      /** Reason */
      reason: string
      /** Risk */
      risk: string
      /** Size Reason */
      size_reason: string
    }
    /** ProfileUpdate */
    ProfileUpdate: {
      /** Analytics Opt In */
      analytics_opt_in?: boolean | null
      /** Display Name */
      display_name?: string | null
      /** Leaderboard Opt In */
      leaderboard_opt_in?: boolean | null
    }
    /** PublicConfig */
    PublicConfig: {
      /** Auth */
      auth:
        | components['schemas']['GuestAuthConfig']
        | components['schemas']['FirebaseAuthConfig']
    }
    /** Purchase */
    Purchase: {
      /** Idempotency Key */
      idempotency_key: string
      /** Item Id */
      item_id: string
      /**
       * Policy Version
       * @default 1
       * @constant
       */
      policy_version?: '1'
    }
    /** Response */
    Response: {
      answer: components['schemas']['Answer']
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Review */
    Review: {
      audit: components['schemas']['Audit']
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Start */
    Start: {
      /** Idempotency Key */
      idempotency_key: string
      /** Module Id */
      module_id?: string | null
      /** Room Id */
      room_id?: string | null
    }
    /** StartLevel */
    StartLevel: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Purpose
       * @default practice
       * @enum {string}
       */
      purpose?: 'practice' | 'bonus'
    }
    /** StepAnswer */
    StepAnswer: {
      /** Acknowledged */
      acknowledged?: boolean | null
      /** Assignments */
      assignments?: {
        [key: string]: string
      } | null
      /** Confidence */
      confidence?: number | null
      /** Option Id */
      option_id?: string | null
    }
    /** Submission */
    Submission: {
      /** Answers */
      answers: components['schemas']['Answer'][]
      /** Idempotency Key */
      idempotency_key: string
      /** Reflection */
      reflection: string
    }
    /** SubmitStep */
    SubmitStep: {
      answer: components['schemas']['StepAnswer']
      /** Idempotency Key */
      idempotency_key: string
    }
    /** TickCommand */
    TickCommand: {
      /** Expected Tick */
      expected_tick: number
      /** Idempotency Key */
      idempotency_key: string
    }
    /** TickOrder */
    TickOrder: {
      /** Expected Tick */
      expected_tick: number
      /** Idempotency Key */
      idempotency_key: string
      plan: components['schemas']['Plan']
      /** Price */
      price?: string | null
      /** Quantity */
      quantity: number
      /**
       * Side
       * @enum {string}
       */
      side: 'buy' | 'sell'
      /**
       * Symbol
       * @enum {string}
       */
      symbol: 'NORTH' | 'HARBOR' | 'PLAIN' | 'COVE'
      /**
       * Type
       * @enum {string}
       */
      type: 'market' | 'limit' | 'stop'
    }
    /** UserProfile */
    UserProfile: {
      /** Activity Days */
      activity_days: string[]
      /**
       * Activity Timezone
       * @constant
       */
      activity_timezone: 'UTC'
      /** Analytics Opt In */
      analytics_opt_in: boolean
      /** Completed Lesson Ids */
      completed_lesson_ids: string[]
      /** Display Name */
      display_name: string
      /** Due Review Count */
      due_review_count: number
      /** Game Xp */
      game_xp: number
      /** Id */
      id: string
      /** Leaderboard Opt In */
      leaderboard_opt_in: boolean
      /** Learning Only */
      learning_only: boolean
      /** Learning Xp */
      learning_xp: number
      /** Mastered Module Ids */
      mastered_module_ids: string[]
      /** Player Level */
      player_level: number
      /**
       * Player Level Policy
       * @constant
       */
      player_level_policy: '100-xp-per-level-1'
      /** Xp */
      xp: number
      /**
       * Xp Basis
       * @constant
       */
      xp_basis: 'learning and game events'
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, unknown>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
