// Generated by npm run api:generate. Do not edit manually.
export interface paths {
  '/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Root */
    get: operations['getRoot']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/adventure': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Adventure */
    get: operations['adventure_api_adventure_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/archive': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Archive */
    get: operations['archive_api_archive_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/attempts/{attempt_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Attempt */
    get: operations['get_attempt_api_attempts__attempt_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Attempts */
    get: operations['list_attempts_api_challenges_get']
    put?: never
    /** Start */
    post: operations['start_api_challenges_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges/{attempt_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Resume */
    get: operations['getChallenge']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges/{attempt_id}/abandon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Abandon */
    post: operations['abandon_api_challenges__attempt_id__abandon_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges/{attempt_id}/advance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Advance */
    post: operations['advance_api_challenges__attempt_id__advance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges/{attempt_id}/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete */
    post: operations['complete_api_challenges__attempt_id__complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges/{attempt_id}/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Order */
    post: operations['order_api_challenges__attempt_id__orders_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/challenges/{attempt_id}/orders/{order_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel */
    post: operations['cancel_api_challenges__attempt_id__orders__order_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/config': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Config */
    get: operations['getConfig']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/curriculum': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Curriculum */
    get: operations['get_curriculum_api_curriculum_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/journal': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Journal */
    get: operations['listJournal']
    put?: never
    /** Add Journal */
    post: operations['add_journal_api_journal_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/journal/{entry_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    /** Delete Journal */
    delete: operations['delete_journal_api_journal__entry_id__delete']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/leaderboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Leaderboard */
    get: operations['leaderboard_api_leaderboard_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/learning-runs/{run_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Run */
    get: operations['get_run_api_learning_runs__run_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/learning-runs/{run_id}/simulation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Resume */
    get: operations['resume_api_learning_runs__run_id__simulation_get']
    put?: never
    /** Bind */
    post: operations['bind_api_learning_runs__run_id__simulation_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/learning-runs/{run_id}/simulation/review': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Review */
    post: operations['review_api_learning_runs__run_id__simulation_review_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/learning-runs/{run_id}/steps/{step_id}/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Step */
    post: operations['submit_step_api_learning_runs__run_id__steps__step_id__submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/lessons/{lesson_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Lesson */
    get: operations['get_lesson_api_lessons__lesson_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/lessons/{lesson_id}/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete Lesson */
    post: operations['complete_lesson_api_lessons__lesson_id__complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/levels/{level_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Level */
    get: operations['get_level_api_levels__level_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/levels/{level_id}/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Level */
    post: operations['start_level_api_levels__level_id__runs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/activity': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Activity */
    get: operations['activity_api_me_activity_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/economy': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Wallet */
    get: operations['read_wallet_api_me_economy_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/economy/daily-refresh': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Refresh Daily */
    post: operations['refresh_daily_api_me_economy_daily_refresh_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/economy/login-claims': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login Claim */
    post: operations['login_claim_api_me_economy_login_claims_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/economy/shop': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Shop */
    get: operations['read_shop_api_me_economy_shop_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/economy/shop/purchases': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Purchase */
    post: operations['purchase_api_me_economy_shop_purchases_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/profile': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Profile */
    get: operations['getProfile']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Patch Profile */
    patch: operations['updateProfile']
    trace?: never
  }
  '/api/me/research': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Read Metadata */
    get: operations['read_metadata_api_me_research_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/research/consents': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Consent */
    post: operations['consent_api_me_research_consents_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/research/export/{kind}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Export */
    get: operations['export_api_me_research_export__kind__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/research/metadata': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Set Metadata */
    post: operations['set_metadata_api_me_research_metadata_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/research/withdrawals': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Withdraw */
    post: operations['withdraw_api_me_research_withdrawals_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/rewards': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Inventory */
    get: operations['inventory_api_me_rewards_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/rewards/claims': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Claim */
    post: operations['claim_api_me_rewards_claims_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/me/rewards/equipment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Equip */
    patch: operations['equip_api_me_rewards_equipment_patch']
    trace?: never
  }
  '/api/me/workflow': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Workflow */
    get: operations['workflow_api_me_workflow_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/modules/{module_id}/assessment': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Assessment */
    get: operations['get_assessment_api_modules__module_id__assessment_get']
    put?: never
    /** Complete Assessment */
    post: operations['complete_assessment_api_modules__module_id__assessment_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/modules/{module_id}/assessment-runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Assessment */
    post: operations['start_assessment_api_modules__module_id__assessment_runs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/modules/{module_id}/diagnostic-runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Diagnostic */
    post: operations['start_diagnostic_api_modules__module_id__diagnostic_runs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/modules/{module_id}/map': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Map */
    get: operations['get_map_api_modules__module_id__map_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Resume */
    get: operations['resume_api_multiplayer__lobby_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}/abandon': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Abandon */
    post: operations['abandon_api_multiplayer__lobby_id__abandon_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete */
    post: operations['complete_api_multiplayer__lobby_id__complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Order */
    post: operations['order_api_multiplayer__lobby_id__orders_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}/orders/{order_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel */
    post: operations['cancel_api_multiplayer__lobby_id__orders__order_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Ready */
    post: operations['ready_api_multiplayer__lobby_id__ready_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/{lobby_id}/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start */
    post: operations['start_api_multiplayer__lobby_id__start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/join': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Join */
    post: operations['join_api_multiplayer_join_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/leaderboard': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Leaderboard */
    get: operations['leaderboard_api_multiplayer_leaderboard_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/lobbies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create */
    post: operations['create_api_multiplayer_lobbies_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/matches': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Matches */
    get: operations['matches_api_multiplayer_matches_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/multiplayer/matchmaking': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Matchmaking */
    post: operations['matchmaking_api_multiplayer_matchmaking_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/attempts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Attempts */
    get: operations['list_attempts_api_quizzes_attempts_get']
    put?: never
    /** Start Attempt */
    post: operations['start_attempt_api_quizzes_attempts_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/attempts/{attempt_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Attempt */
    get: operations['get_attempt_api_quizzes_attempts__attempt_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/attempts/{attempt_id}/answers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Answer */
    post: operations['answer_api_quizzes_attempts__attempt_id__answers_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/forms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Forms */
    get: operations['forms_api_quizzes_forms_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/question-bank': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Question Bank */
    get: operations['question_bank_api_quizzes_question_bank_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/rooms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Rooms */
    get: operations['list_rooms_api_quizzes_rooms_get']
    put?: never
    /** Create Room */
    post: operations['create_room_api_quizzes_rooms_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/rooms/{room_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Room */
    get: operations['get_room_api_quizzes_rooms__room_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/rooms/{room_id}/close': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Close Room */
    post: operations['close_room_api_quizzes_rooms__room_id__close_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/rooms/{room_id}/results': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Room Results */
    get: operations['room_results_api_quizzes_rooms__room_id__results_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/rooms/{room_id}/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Room */
    post: operations['start_room_api_quizzes_rooms__room_id__start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/quizzes/rooms/join': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Join Room */
    post: operations['join_room_api_quizzes_rooms_join_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reviews': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Reviews */
    get: operations['reviews_api_reviews_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reviews/{review_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Review */
    get: operations['get_review_api_reviews__review_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reviews/{review_id}/runs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Review */
    post: operations['start_review_api_reviews__review_id__runs_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/reviews/{review_id}/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Review */
    post: operations['submit_review_api_reviews__review_id__submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/session': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Guest Session */
    post: operations['startGuestSession']
    /** Logout */
    delete: operations['logout']
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/simulations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List Sessions */
    get: operations['list_sessions_api_simulations_get']
    put?: never
    /** Start */
    post: operations['start_api_simulations_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/simulations/{session_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Resume */
    get: operations['resume_api_simulations__session_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/simulations/{session_id}/advance': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Advance */
    post: operations['advance_api_simulations__session_id__advance_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/simulations/{session_id}/debrief': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Debrief */
    post: operations['debrief_api_simulations__session_id__debrief_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/simulations/{session_id}/orders': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Order */
    post: operations['order_api_simulations__session_id__orders_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/simulations/{session_id}/orders/{order_id}/cancel': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Cancel */
    post: operations['cancel_api_simulations__session_id__orders__order_id__cancel_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Health Check */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Advance */
    Advance: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Steps
       * @default 1
       */
      steps?: number
    }
    /** Answer */
    Answer: {
      /** Confidence */
      confidence?: number | null
      /** Option Id */
      option_id: string
      /** Question Id */
      question_id: string
    }
    /** Create */
    app__challenges__api__Create: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Mode
       * @default practice
       * @enum {string}
       */
      mode?: 'practice' | 'daily' | 'chapter_entry' | 'chapter_exit'
      /** Module Id */
      module_id?: string | null
      /**
       * Opponent Count
       * @default 1
       */
      opponent_count?: number
    }
    /** Command */
    app__economy__Command: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Policy Version
       * @default 1
       * @constant
       */
      policy_version?: '1'
    }
    /** Command */
    app__learning_runs__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Join */
    app__multiplayer__api__Join: {
      /** Code */
      code: string
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Command */
    app__quizzes__api__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Join */
    app__quizzes__api__Join: {
      /** Idempotency Key */
      idempotency_key: string
      /** Join Code */
      join_code: string
    }
    /** Command */
    app__research__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Command */
    app__simulation__api__Command: {
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Create */
    app__simulation__api__Create: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Mode
       * @default guided
       * @enum {string}
       */
      mode?: 'guided' | 'endless'
    }
    /** Audit */
    Audit: {
      /** Engine Version */
      engine_version: number
      /** No Order Reason */
      no_order_reason: ('no_thesis_supplied' | 'current_ask_above_cap') | null
      /** Observation Token */
      observation_token?: string | null
      /** Orders */
      orders: components['schemas']['AuditOrder'][]
      /** Price Limit Guarantees Fill */
      price_limit_guarantees_fill: boolean
      /** Session Fees */
      session_fees: string
      /** Tick */
      tick: number
    }
    /** AuditOrder */
    AuditOrder: {
      /** Filled Quantity */
      filled_quantity: number
      /** Limit Price */
      limit_price: string
      /** Order Id */
      order_id: string
      /**
       * Status
       * @enum {string}
       */
      status:
        'open' | 'partial' | 'filled' | 'cancelled' | 'expired' | 'rejected'
    }
    /** Claim */
    Claim: {
      /** Idempotency Key */
      idempotency_key: string
      /** Item Id */
      item_id: string
    }
    /** Consent */
    Consent: {
      /** Accepted */
      accepted: boolean
      /** Idempotency Key */
      idempotency_key: string
      /** Policy Digest */
      policy_digest: string
      /** Policy Version */
      policy_version: string
    }
    /** CreateRoom */
    CreateRoom: {
      /**
       * Attempt Limit
       * @default 1
       */
      attempt_limit?: number
      /** Idempotency Key */
      idempotency_key: string
      /** Question Ids */
      question_ids: string[]
      /** Title */
      title: string
    }
    /** Debrief */
    Debrief: {
      /** Idempotency Key */
      idempotency_key: string
      /** Reflection */
      reflection: string
    }
    /** Equipment */
    Equipment: {
      /** Avatar Id */
      avatar_id?: string | null
      /** Idempotency Key */
      idempotency_key: string
      /** Title Id */
      title_id?: string | null
    }
    /** FirebaseAuthConfig */
    FirebaseAuthConfig: {
      /** Firebase Project Id */
      firebase_project_id: string
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      mode: 'firebase'
    }
    /** GuestAuthConfig */
    GuestAuthConfig: {
      /** Firebase Project Id */
      firebase_project_id: null
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      mode: 'guest'
    }
    /** GuestSession */
    GuestSession: {
      /**
       * Auth Mode
       * @constant
       */
      auth_mode: 'guest'
      /** Expires At */
      expires_at: string
      /** Profile Id */
      profile_id: string
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** JournalCreate */
    JournalCreate: {
      /** Lesson Id */
      lesson_id?: string | null
      /** Text */
      text: string
    }
    /** Metadata */
    Metadata: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Prior Knowledge
       * @enum {string}
       */
      prior_knowledge: 'unknown' | 'none' | 'some' | 'experienced'
    }
    /** Order */
    Order: {
      /** Idempotency Key */
      idempotency_key: string
      plan: components['schemas']['Plan']
      /** Price */
      price?: string | null
      /** Quantity */
      quantity: number
      /**
       * Side
       * @enum {string}
       */
      side: 'buy' | 'sell'
      /**
       * Symbol
       * @enum {string}
       */
      symbol: 'NORTH' | 'HARBOR' | 'PLAIN' | 'COVE'
      /**
       * Type
       * @enum {string}
       */
      type: 'market' | 'limit' | 'stop'
    }
    /** Plan */
    Plan: {
      /** Exit */
      exit: string
      /** Max Loss */
      max_loss: string
      /** Reason */
      reason: string
      /** Risk */
      risk: string
      /** Size Reason */
      size_reason: string
    }
    /** ProfileUpdate */
    ProfileUpdate: {
      /** Analytics Opt In */
      analytics_opt_in?: boolean | null
      /** Display Name */
      display_name?: string | null
      /** Leaderboard Opt In */
      leaderboard_opt_in?: boolean | null
    }
    /** PublicConfig */
    PublicConfig: {
      /** Auth */
      auth:
        | components['schemas']['GuestAuthConfig']
        | components['schemas']['FirebaseAuthConfig']
    }
    /** Purchase */
    Purchase: {
      /** Idempotency Key */
      idempotency_key: string
      /** Item Id */
      item_id: string
      /**
       * Policy Version
       * @default 1
       * @constant
       */
      policy_version?: '1'
    }
    /** Response */
    Response: {
      answer: components['schemas']['Answer']
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Review */
    Review: {
      audit: components['schemas']['Audit']
      /** Idempotency Key */
      idempotency_key: string
    }
    /** Start */
    Start: {
      /** Idempotency Key */
      idempotency_key: string
      /** Module Id */
      module_id?: string | null
      /** Room Id */
      room_id?: string | null
    }
    /** StartLevel */
    StartLevel: {
      /** Idempotency Key */
      idempotency_key: string
      /**
       * Purpose
       * @default practice
       * @enum {string}
       */
      purpose?: 'practice' | 'bonus'
    }
    /** StepAnswer */
    StepAnswer: {
      /** Acknowledged */
      acknowledged?: boolean | null
      /** Assignments */
      assignments?: {
        [key: string]: string
      } | null
      /** Confidence */
      confidence?: number | null
      /** Option Id */
      option_id?: string | null
    }
    /** Submission */
    Submission: {
      /** Answers */
      answers: components['schemas']['Answer'][]
      /** Idempotency Key */
      idempotency_key: string
      /** Reflection */
      reflection: string
    }
    /** SubmitStep */
    SubmitStep: {
      answer: components['schemas']['StepAnswer']
      /** Idempotency Key */
      idempotency_key: string
    }
    /** TickCommand */
    TickCommand: {
      /** Expected Tick */
      expected_tick: number
      /** Idempotency Key */
      idempotency_key: string
    }
    /** TickOrder */
    TickOrder: {
      /** Expected Tick */
      expected_tick: number
      /** Idempotency Key */
      idempotency_key: string
      plan: components['schemas']['Plan']
      /** Price */
      price?: string | null
      /** Quantity */
      quantity: number
      /**
       * Side
       * @enum {string}
       */
      side: 'buy' | 'sell'
      /**
       * Symbol
       * @enum {string}
       */
      symbol: 'NORTH' | 'HARBOR' | 'PLAIN' | 'COVE'
      /**
       * Type
       * @enum {string}
       */
      type: 'market' | 'limit' | 'stop'
    }
    /** UserProfile */
    UserProfile: {
      /** Activity Days */
      activity_days: string[]
      /**
       * Activity Timezone
       * @constant
       */
      activity_timezone: 'UTC'
      /** Analytics Opt In */
      analytics_opt_in: boolean
      /** Completed Lesson Ids */
      completed_lesson_ids: string[]
      /** Display Name */
      display_name: string
      /** Due Review Count */
      due_review_count: number
      /** Game Xp */
      game_xp: number
      /** Id */
      id: string
      /** Leaderboard Opt In */
      leaderboard_opt_in: boolean
      /** Learning Only */
      learning_only: boolean
      /** Learning Xp */
      learning_xp: number
      /** Mastered Module Ids */
      mastered_module_ids: string[]
      /** Player Level */
      player_level: number
      /**
       * Player Level Policy
       * @constant
       */
      player_level_policy: '100-xp-per-level-1'
      /** Xp */
      xp: number
      /**
       * Xp Basis
       * @constant
       */
      xp_basis: 'learning and game events'
    }
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, unknown>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getRoot: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  adventure_api_adventure_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  archive_api_archive_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_attempt_api_attempts__attempt_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_attempts_api_challenges_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  start_api_challenges_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__challenges__api__Create']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  getChallenge: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  abandon_api_challenges__attempt_id__abandon_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  advance_api_challenges__attempt_id__advance_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Advance']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  complete_api_challenges__attempt_id__complete_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Debrief']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  order_api_challenges__attempt_id__orders_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Order']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_api_challenges__attempt_id__orders__order_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
        order_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  getConfig: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PublicConfig']
        }
      }
    }
  }
  get_curriculum_api_curriculum_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  listJournal: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  add_journal_api_journal_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['JournalCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  delete_journal_api_journal__entry_id__delete: {
    parameters: {
      query?: never
      header?: never
      path: {
        entry_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  leaderboard_api_leaderboard_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_run_api_learning_runs__run_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  resume_api_learning_runs__run_id__simulation_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  bind_api_learning_runs__run_id__simulation_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__learning_runs__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  review_api_learning_runs__run_id__simulation_review_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Review']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_step_api_learning_runs__run_id__steps__step_id__submit_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        run_id: string
        step_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SubmitStep']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_lesson_api_lessons__lesson_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        lesson_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  complete_lesson_api_lessons__lesson_id__complete_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lesson_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Submission']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_level_api_levels__level_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        level_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_level_api_levels__level_id__runs_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        level_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['StartLevel']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  activity_api_me_activity_get: {
    parameters: {
      query?: {
        end_date?: string | null
        start_date?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_wallet_api_me_economy_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  refresh_daily_api_me_economy_daily_refresh_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__economy__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  login_claim_api_me_economy_login_claims_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__economy__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_shop_api_me_economy_shop_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  purchase_api_me_economy_shop_purchases_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Purchase']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  getProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserProfile']
        }
      }
    }
  }
  updateProfile: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ProfileUpdate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserProfile']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  read_metadata_api_me_research_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  consent_api_me_research_consents_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Consent']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  export_api_me_research_export__kind__get: {
    parameters: {
      query?: {
        cursor?: string | null
        limit?: number
      }
      header?: never
      path: {
        kind: 'learning-runs' | 'learning-attempts' | 'ai-challenges'
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  set_metadata_api_me_research_metadata_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Metadata']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  withdraw_api_me_research_withdrawals_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__research__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  inventory_api_me_rewards_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  claim_api_me_rewards_claims_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Claim']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  equip_api_me_rewards_equipment_patch: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Equipment']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  workflow_api_me_workflow_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_assessment_api_modules__module_id__assessment_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        module_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  complete_assessment_api_modules__module_id__assessment_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        module_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Submission']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_assessment_api_modules__module_id__assessment_runs_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        module_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__learning_runs__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_diagnostic_api_modules__module_id__diagnostic_runs_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        module_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__learning_runs__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_map_api_modules__module_id__map_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        module_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  resume_api_multiplayer__lobby_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  abandon_api_multiplayer__lobby_id__abandon_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  complete_api_multiplayer__lobby_id__complete_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Debrief']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  order_api_multiplayer__lobby_id__orders_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TickOrder']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_api_multiplayer__lobby_id__orders__order_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
        order_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TickCommand']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  ready_api_multiplayer__lobby_id__ready_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TickCommand']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_api_multiplayer__lobby_id__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        lobby_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  join_api_multiplayer_join_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__multiplayer__api__Join']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  leaderboard_api_multiplayer_leaderboard_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  create_api_multiplayer_lobbies_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  matches_api_multiplayer_matches_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  matchmaking_api_multiplayer_matchmaking_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_attempts_api_quizzes_attempts_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  start_attempt_api_quizzes_attempts_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Start']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_attempt_api_quizzes_attempts__attempt_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  answer_api_quizzes_attempts__attempt_id__answers_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        attempt_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Response']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  forms_api_quizzes_forms_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  question_bank_api_quizzes_question_bank_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  list_rooms_api_quizzes_rooms_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  create_room_api_quizzes_rooms_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateRoom']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_room_api_quizzes_rooms__room_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        room_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  close_room_api_quizzes_rooms__room_id__close_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        room_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__quizzes__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  room_results_api_quizzes_rooms__room_id__results_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        room_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_room_api_quizzes_rooms__room_id__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        room_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__quizzes__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  join_room_api_quizzes_rooms_join_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__quizzes__api__Join']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  reviews_api_reviews_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_review_api_reviews__review_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        review_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_review_api_reviews__review_id__runs_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        review_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__learning_runs__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_review_api_reviews__review_id__submit_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        review_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Submission']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  startGuestSession: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GuestSession']
        }
      }
    }
  }
  logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
    }
  }
  list_sessions_api_simulations_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  start_api_simulations_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Create']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  resume_api_simulations__session_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  advance_api_simulations__session_id__advance_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Advance']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  debrief_api_simulations__session_id__debrief_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Debrief']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  order_api_simulations__session_id__orders_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['Order']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  cancel_api_simulations__session_id__orders__order_id__cancel_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        order_id: string
        session_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['app__simulation__api__Command']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
}
